apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: primary
  template:
    metadata:
      labels:
        app: primary
    spec:
      containers:
        - name: main
          image: argoproj/rollouts-demo:green
          ports:
            - containerPort: 80
